mv to ofw

diff --git a/src/scripts/vpn-watch b/src/scripts/vpn-watch
--- a/src/scripts/vpn-watch
+++ b/src/scripts/vpn-watch
@@ -1,14 +1,12 @@
 #!/bin/sh
 #
-# IPCop script - vpn-watch
+# Openfirewall script - vpn-watch
 #
 # This code is distributed under the terms of the GPL
 #
 # (c) Daniel Berlin <daniel berlin_itechnology de> - Check for
 #   remote peer with dynamic IPs and restart when change
 #   is detected. Works with DPD which is not perfect!
-#
-# 2006: Franck - adapted original script to fit in IPCop 1.4
 #
 #
 # This program is free software; you can redistribute it and/or modify
@@ -27,8 +25,8 @@
 # Configuration
 #
 
-VPN_CONFIG='/var/ipcop/ipsec/config'    # Location of IPCop's vpn configuration file
-SETTINGS='/var/ipcop/ipsec/settings'    # and settings
+VPN_CONFIG='/var/ofw/ipsec/config'    # Location of Openfirewall's vpn configuration file
+SETTINGS='/var/ofw/ipsec/settings'    # and settings
 
 CHECK_INTERVAL='60'                     # Check this often (in seconds)
 DNS_RESOLVE_TRIES='4'                   # Try to resolve IPs this often (each try takes max. 2 seconds)
@@ -39,7 +37,7 @@ case "$1" in
         test "${VPN_WATCH}" != "on"  && exit 1          # not activated, cannot start!
 
         if test ! -r "$VPN_CONFIG"; then
-            echo 'Error: cannot read IPCop VPN configuration file; exit.' >&2
+            echo 'Error: cannot read Openfw VPN configuration file; exit.' >&2
             exit 1
         fi
 
